services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - clean_crm_postgres:/var/lib/postgresql/data

  clean-crm:
    build:
      context: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CRM_JWT_SECRET: ${CRM_JWT_SECRET}
      CRM_ADMIN_USERNAME: ${CRM_ADMIN_USERNAME}
      CRM_ADMIN_PASSWORD: ${CRM_ADMIN_PASSWORD}
      CRM_ADMIN_EMAIL: ${CRM_ADMIN_EMAIL}
    depends_on:
      - db
    ports:
      - "8000:8000"
    image: clean-crm:latest

volumes:
  clean_crm_postgres: